package com.example.translatorapp_mvvm_kotlin.model

import com.example.translatorapp_mvvm_kotlin.BuildConfig

class Constants {

    companion object {
        const val TEXT_TO_SPEECH_API_URL = "https://voicerss-text-to-speech.p.rapidapi.com/"
        const val TEXT_TO_SPEECH_RAPID_KEY = BuildConfig.TEXT_TO_SPEECH_RAPID_KEY
        const val TEXT_TO_SPEECH_API_KEY = BuildConfig.TEXT_TO_SPEECH_API_KEY
        const val API_URL = "https://api.mymemory.translated.net/"
        val countryCodeList = listOf(
            "am-ET", "ar-SA", "be-BY", "bem-ZM", "bi-VU", "bjs-BB",
            "bn-IN", "bo-CN", "br-FR", "bs-BA", "ca-ES", "cop-EG",
            "cs-CZ", "cy-GB", "da-DK", "dz-BT", "de-DE", "dv-MV",
            "el-GR", "en-GB", "es-ES", "et-EE", "eu-ES", "fa-IR",
            "fi-FI", "fn-FNG", "fo-FO", "fr-FR", "gl-ES", "gu-IN",
            "ha-NE", "he-IL", "hi-IN", "hr-HR", "hu-HU", "id-ID",
            "is-IS", "it-IT", "ja-JP", "kk-KZ", "km-KM", "kn-IN",
            "ko-KR", "ku-TR", "ky-KG", "la-VA", "lo-LA", "lv-LV",
            "men-SL", "mg-MG", "mi-NZ", "ms-MY", "mt-MT", "my-MM",
            "ne-NP", "niu-NU", "nl-NL", "no-NO", "ny-MW", "ur-PK",
            "pau-PW", "pa-IN", "ps-PK", "pis-SB", "pl-PL", "pt-PT",
            "rn-BI", "ro-RO", "ru-RU", "sg-CF", "si-LK", "sk-SK",
            "sm-WS", "sn-ZW", "so-SO", "sq-AL", "sr-RS", "sv-SE",
            "sw-SZ", "ta-LK", "te-IN", "tet-TL", "tg-TJ", "th-TH",
            "ti-TI", "tk-TM", "tl-PH", "tn-BW", "to-TO", "tr-TR",
            "uk-UA", "uz-UZ", "vi-VN", "wo-SN", "xh-ZA", "yi-YD",
            "zu-ZA"
        )
        val countryNameList = listOf(
            "Amharic",
            "Arabic",
            "Bielarus",
            "Bemba",
            "Bislama",
            "Bajan",
            "Bengali",
            "Tibetan",
            "Breton",
            "Bosnian",
            "Catalan",
            "Coptic",
            "Czech",
            "Welsh",
            "Danish",
            "Dzongkha",
            "German",
            "Maldivian",
            "Greek",
            "English",
            "Spanish",
            "Estonian",
            "Basque",
            "Persian",
            "Finnish",
            "Fanagalo",
            "Faroese",
            "French",
            "Galician",
            "Gujarati",
            "Hausa",
            "Hebrew",
            "Hindi",
            "Croatian",
            "Hungarian",
            "Indonesian",
            "Icelandic",
            "Italian",
            "Japanese",
            "Kazakh",
            "Khmer",
            "Kannada",
            "Korean",
            "Kurdish",
            "Kyrgyz",
            "Latin",
            "Lao",
            "Latvian",
            "Mende",
            "Malagasy",
            "Maori",
            "Malay",
            "Maltese",
            "Burmese",
            "Nepali",
            "Niuean",
            "Dutch",
            "Norwegian",
            "Nyanja",
            "Pakistani",
            "Palauan",
            "Panjabi",
            "Pashto",
            "Pijin",
            "Polish",
            "Portuguese",
            "Kirundi",
            "Romanian",
            "Russian",
            "Sango",
            "Sinhala",
            "Slovak",
            "Samoan",
            "Shona",
            "Somali",
            "Albanian",
            "Serbian",
            "Swedish",
            "Swahili",
            "Tamil",
            "Telugu",
            "Tetum",
            "Tajik",
            "Thai",
            "Tigrinya",
            "Turkmen",
            "Tagalog",
            "Tswana",
            "Tongan",
            "Turkish",
            "Ukrainian",
            "Uzbek",
            "Vietnamese",
            "Wolof",
            "Xhosa",
            "Yiddish",
            "Zulu",

            )
    }
}